### ISSUE TITLE
google/golang-runtime deprecated 

### ISSUE THREAD

**Issue by orcaman** [rcadena/ebs-docker-hello#2]
Hi there,

Great tutorial!

BTW, `google/golang-runtime` doesn't work anymore (it's been deprecated: https://hub.docker.com/r/google/golang-runtime/), need to use `golang` instead (https://hub.docker.com/_/golang/)

Cheers

**Comment by rcadena** [comment]
Thanks @orcaman .  I'll update the repo to reflect this.
